# Generated by Django 6.0.3 on 2026-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='handyman_per_location',
            field=models.TextField(null=True),
        ),
    ]
