# Generated by Django 6.0.3 on 2026-04-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_handyman_per_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='handyman_per_location',
            field=models.CharField(null=True),
        ),
    ]
