# Generated by Django 6.0.4 on 2026-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_withdrawal_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_withdrawal_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_withdrawal_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='handyman_payment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
