# Generated by Django 6.0.3 on 2026-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_admin_withdrawal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='handyman_withdrawal_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
