# Generated by Django 5.2.16 on 2026-08-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
