# Generated by Django 6.0.6 on 2026-07-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default price for this category', max_digits=10, null=True),
        ),
    ]
