# Generated by Django 6.0.6 on 2026-06-28 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
    ]
