# Generated by Django 6.0.6 on 2026-07-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('handyman', 'Handyman')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
