# Generated by Django 6.0.3 on 2026-06-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_supportconversation_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support_images/'),
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
