# Generated by Django 6.0.6 on 2026-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_bookingmessage_image_supportmessage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/'),
        ),
        migrations.AddField(
            model_name='bookingmessage',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/'),
        ),
        migrations.AddField(
            model_name='bookingmessage',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='chat_video_thumbnails/'),
        ),
    ]
