# Generated by Django 6.0.6 on 2026-07-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_bookingmessage_audio_bookingmessage_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
