# Generated by Django 6.0.3 on 2026-04-03 13:15

import django.db.models.deletion
import django.utils.timezone
import handymen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0005_alter_location_handyman_per_location'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handyman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=handymen.models.upload_handyman_thumbnail)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('two_fa_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups this handyman belongs to.', related_name='handyman_set', related_query_name='handyman', to='auth.group', verbose_name='groups')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handymen', to='locations.location')),
                ('services', models.ManyToManyField(blank=True, related_name='handymen', to='services.service')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='handyman_set', related_query_name='handyman', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Handyman',
                'verbose_name_plural': 'Handymen',
            },
        ),
    ]
