# Generated by Django 6.0.4 on 2026-05-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handyman',
            name='availability',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
