# Generated by Django 6.0.4 on 2026-05-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymen', '0002_alter_handyman_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='handyman',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from 1.00 to 10.00', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='handyman',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
