# Generated by Django 6.0.3 on 2026-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymen', '0003_handyman_average_rating_handyman_total_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='handyman',
            name='subscription_level',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
