# Generated by Django 6.0.3 on 2026-06-13 23:49

import django.db.models.deletion
import handymen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymen', '0006_handyman_id_card_back_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=handymen.models.upload_job_picture)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_pictures', to='handymen.handyman')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
