# Generated by Django 6.0.3 on 2026-06-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymen', '0007_jobpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='handyman',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
