# Generated by Django 6.0.6 on 2026-07-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handymen', '0009_remove_handyman_is_banned'),
        ('services', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handyman',
            name='subscription_level',
        ),
        migrations.AddField(
            model_name='handyman',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='handymen', to='services.category'),
        ),
    ]
