"""
Django settings for handyman project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import json
from pathlib import Path

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── Load .env file ─────────────────────────────────────────────────
env_path = BASE_DIR.parent / '.env'
try:
    from dotenv import load_dotenv
    if env_path.exists():
        load_dotenv(dotenv_path=env_path)
        print(f"[SETTINGS] Loaded .env from {env_path}")
    else:
        print(f"[SETTINGS] No .env file found at {env_path}")
except ImportError:
    print("[SETTINGS] python-dotenv not installed. Run: pip install python-dotenv")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# ── MeSomb Configuration ───────────────────────────────────────────
# Load from environment variables for security
MESOMB_ACCESS_KEY = os.getenv('MESOMB_ACCESS_KEY', 'e3c418a5-043f-4a2b-aeb4-4c8207384932 ')
MESOMB_SECRET_KEY = os.getenv('MESOMB_SECRET_KEY', '9733680c-1139-4901-9fd3-59802a786af6')
MESOMB_APPLICATION_KEY = os.getenv('MESOMB_APPLICATION_KEY', 'e96d73249360397e619946b8913a87763658bc3d')

# Webhook security (optional but recommended)
MESOMB_WEBHOOK_SECRET = os.getenv('MESOMB_WEBHOOK_SECRET', 'your_webhook_secret_here')

# Environment settings
MESOMB_ENVIRONMENT = os.getenv('MESOMB_ENVIRONMENT', 'sandbox')  # Change to 'production' when ready

# Webhook URLs (for ngrok testing - update with your ngrok URL)
NGROK_URL = os.getenv('NGROK_URL', 'https://sharpie-carless-rimless.ngrok-free.dev')
WEBHOOK_BASE_URL = f"{NGROK_URL}/api/payments/webhooks"

# Split percentages
PLATFORM_FEE_PERCENT  = 0.30   # 30% goes to admin
HANDYMAN_CUT_PERCENT  = 0.70   # 70% goes to handyman



# Correct path: firebase-service-account.json should be in the same folder as settings.py
FIREBASE_SERVICE_ACCOUNT_PATH = BASE_DIR / 'handyman/firebase-service-account.json'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+1-rgp&271)w)qu%guby%7c9dw!*(($1lnfc5b2r+eq&6favh7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.43.188', 'localhost', '127.0.0.1']

ALLOWED_HOSTS = ['*']          # Allows all hosts during development

# ID verification sends two base64 images in one JSON body
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB

AUTH_USER_MODEL = 'users.User'

# ── Google OAuth Configuration ───────────────────────────────────
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', '')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':(
       'rest_framework_simplejwt.authentication.JWTAuthentication',
       'rest_framework.authentication.TokenAuthentication',

    )
}
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS':  True,   # each refresh gives a new refresh token
    'BLACKLIST_AFTER_ROTATION': True, # old refresh tokens can't be reused
}


AXES_FAILURE_LIMIT      = 5
AXES_COOLOFF_TIME       = timedelta(hours=1)   # must be timedelta, not integer 1
AXES_LOCKOUT_PARAMETERS = [['username']]        # ← lock by USERNAME ONLY, not IP
AXES_RESET_ON_SUCCESS   = True
AXES_ENABLED            = True


CORS_ALLOW_ALL_ORIGINS = True
# Application definition


INSTALLED_APPS = [
    'daphne',
    'channels',
    'axes',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'allauth',
    'rest_framework_simplejwt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth.account',
    'dj_rest_auth.registration',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'handyman',
    'bookings',
    'services',
    'users',
    'locations',
    'handymen',
    'chats',
    'payments',
    'notifications.apps.NotificationsConfig',
    'ratings',
]

SITE_ID = 1 


ASGI_APPLICATION = 'handyman.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"  # Use Redis in production
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    "allauth.account.middleware.AccountMiddleware"

]


AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

]


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_OAUTH_CLIENT_SECRET'),
        }
    }
}


ROOT_URLCONF = 'handyman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Daphne

# WSGI_APPLICATION = 'handyman.wsgi.application'

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     }
# }

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'handyman_db',
        'USER': 'postgres',        # The default PostgreSQL username
        'PASSWORD': '0000', # The password you set during installation
        'HOST': '127.0.0.1',       # Or 'localhost'
        'PORT': '5432',            # The default PostgreSQL port
    }
}

try:
    with open(FIREBASE_SERVICE_ACCOUNT_PATH, 'r', encoding='utf-8') as f:
        FIREBASE_SERVICE_ACCOUNT = json.load(f)
    print("✅ Firebase service account loaded successfully")
except FileNotFoundError:
    FIREBASE_SERVICE_ACCOUNT = None
    print(f"⚠️  Warning: firebase-service-account.json not found at {FIREBASE_SERVICE_ACCOUNT_PATH}")
except json.JSONDecodeError:
    FIREBASE_SERVICE_ACCOUNT = None
    print("❌ Error: firebase-service-account.json is not valid JSON")
except Exception as e:
    FIREBASE_SERVICE_ACCOUNT = None
    print(f"❌ Error loading Firebase service account: {e}")

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Logging configuration — ensure payment debug output is visible in terminal
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {name} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'payments': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'bookings': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}